// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG7fmUeiVSIVIzjiPI1zwXy3DISVq55wM',
    appId: '1:887912872289:web:2555ebde2852e24c2cad20',
    messagingSenderId: '887912872289',
    projectId: 'e-attend-e95ad',
    authDomain: 'e-attend-e95ad.firebaseapp.com',
    storageBucket: 'e-attend-e95ad.firebasestorage.app',
    measurementId: 'G-8E6RP78P9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB01SIfB1PfLgeUIJ8Rag8qGeagMfN8pts',
    appId: '1:887912872289:android:6f7046731bad731d2cad20',
    messagingSenderId: '887912872289',
    projectId: 'e-attend-e95ad',
    storageBucket: 'e-attend-e95ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy6cDx-yg43UbOVayWGUuX0Q-rb71G2Gs',
    appId: '1:887912872289:ios:0a442a966b9460d72cad20',
    messagingSenderId: '887912872289',
    projectId: 'e-attend-e95ad',
    storageBucket: 'e-attend-e95ad.firebasestorage.app',
    iosBundleId: 'com.example.eAttend',
  );

}